logging:
  level: info
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1ns
      batch_size: 1
      count: 10

#    buffer:
#      type: "memory"
#      capacity: 5
#      timeout: 5s
    pipeline:
      thread_num: 10
      processors:
#        - type: "batch"
#          count: 3
#          timeout_ms: 10000
#          data_type: "binary"
        - type: "json_to_arrow"

        - type: "sql"
          query: "SELECT sum(value),avg(value) ,111 as x FROM flow  group by sensor"
        - type: "arrow_to_json"
        - type: "sql"
          query: "SELECT *,cast( __value__  as string) as y FROM flow "


    output:
      type: "stdout"
