# generate示例配置
logging:
  level: trace
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1s
      batch_size: 1


    pipeline:
      thread_num: 4
      processors:
        - type: "batch"
          count: 3
          timeout_ms: 10000
          data_type: "binary"
        - type: "json"
        - type: "sql"
          # SQL查询语句，支持标准SQL语法
          query: "SELECT * FROM flow WHERE value >= 10"
        - type: "json"


    output:
      type: "stdout"
