# generate示例配置
logging:
  level: trace
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10.0, "sensor": "temp_1" }'
      interval: 1s
      batch_size: 10




    pipeline:
      thread_num: 4
      processors:
        - type: "json"
          mode: "to_arrow"
        - type: "sql"
          # SQL查询语句，支持标准SQL语法
          query: "SELECT count(timestamp) as timestamp, sum(value) as value, cast(count(sensor) as string) as  sensor FROM flow WHERE value >= 10 order by sensor"
        - type: "protobuf"
          mode: "from_arrow"
          proto_directory: "examples/"
          message_type: "message.Message"
        - type: "protobuf"
          mode: "to_arrow"
          proto_directory: "examples/"
          message_type: "message.Message"
        - type: "json"
          mode: "from_arrow"

    output:
      type: "stdout"
