# proto 示例配置
logging:
  level: trace
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10.0, "sensor": "temp_1" }'
      interval: 1s
      batch_size: 1

    buffer:
      type: "memory"
      capacity: 10
      timeout: 10s



    pipeline:
      thread_num: 4
      processors:
        - type: "json_to_arrow"
        - type: "sql"
          # SQL查询语句，支持标准SQL语法
          query: "SELECT count(timestamp) as timestamp, sum(value) as value, cast(count(sensor) as string) as  sensor FROM flow WHERE value >= 10 order by sensor"
        - type: "arrow_to_protobuf"
          proto_inputs:
            - "examples/"
          message_type: "message.Message"
        - type: "protobuf_to_arrow"
          proto_inputs:
            - "examples/"
          message_type: "message.Message"

    output:
      type: "stdout"
