logging:
  level: info
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1s
      batch_size: 10

    pipeline:
      thread_num: 4
      processors:
        - type: "json_to_arrow"
        - type: "sql"
          query: "SELECT * FROM flow WHERE value >= 10"

    output:
      type: "s3"  
      provider: "aws"  # /aws/gcp
      bucket: "arkflow"
      region: "ap-northeast-2"
      credentials:
        access_key_id: "your access key id"
        secret_access_key: "your secret access key"
      path: "test"  
      prefix: "arkflow" 
      format: "JSON"         #json/csv/parquet  
      compression: "gzip"   #/gzip/bzip2

    error_output:
      type: "stdout"