[package]
name = "arkflow-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true



[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
async-trait = { workspace = true }
futures-util = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
humantime = { workspace = true }

tracing = { workspace = true }

datafusion = { workspace = true }
datafusion-functions-json = "*"
datafusion-table-providers = { version = "0.4", features = ["mysql", "postgres", "duckdb", "sqlite"] }
spiceai_duckdb_fork = "=1.2.1"
arrow-json = { workspace = true }
prost-reflect = { workspace = true }
prost-types = { workspace = true }
protobuf-parse = { workspace = true }
protobuf = { workspace = true }

lazy_static = { workspace = true }

axum = { workspace = true }
reqwest = { workspace = true }
tower = "0.5"
tower-http = { version = "0.4", features = ["cors", "trace"] }
base64 = "0.22"

colored = { workspace = true }
flume = { workspace = true }
rumqttc = { workspace = true }

# Kafka
aws-msk-iam-sasl-signer = { workspace = true }
rdkafka = { workspace = true }
rdkafka-sys = { workspace = true }
sasl2-sys = { workspace = true }

# arkflow
arkflow-core = { workspace = true }

[patch.crates-io]
duckdb = { package = "spiceai_duckdb_fork", version = "1.2.1" }

[dev-dependencies]
tempfile = { workspace = true }
mockall = { workspace = true }
